<a href="https://colab.research.google.com/github/kianahs/XGBoost_Diabet_Classifier/blob/master/classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd
from pandas.api.types import is_string_dtype
from pandas.api.types import is_numeric_dtype
import numbers

# **part 1**

In [31]:
df = pd.read_csv('diabetes.csv')
df.head()

,Unnamed: 0,Diabetes_binary,HighBP,High Cholesterol,Cholesterol Check,BMI,Smoker,Stroke,HeartDiseaseorAttack,Physical Activity,Fruits,Veggies,Heavy Alcohol Consumption,Any Health Care,No Doctor because of Cost,General Health,Mental Health,Physical Health,Difficulty Walking,Sex,Age,Education,Income
0,0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,Medium,5.0,30.0,0.0,male,4.0,Cat6,Cat8
1,1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,Medium,0.0,0.0,0.0,male,12.0,Cat6,Cat8
2,2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,High,0.0,10.0,0.0,male,13.0,Cat6,Cat8
3,3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,Medium,0.0,3.0,0.0,male,11.0,Cat6,Cat8
4,4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,Good,0.0,0.0,0.0,female,8.0,Cat5,Cat8

In [32]:
df = df.drop(['Unnamed: 0'], axis=1)
print(df.columns)
pd.set_option("display.max_columns", None)
df

Index(['Diabetes_binary', 'HighBP', 'High Cholesterol', 'Cholesterol Check',
       'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'Physical Activity',
       'Fruits', 'Veggies', 'Heavy Alcohol Consumption', 'Any Health Care',
       'No Doctor because of Cost', 'General Health', 'Mental Health',
       'Physical Health', 'Difficulty Walking', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='object')

,Diabetes_binary,HighBP,High Cholesterol,Cholesterol Check,BMI,Smoker,Stroke,HeartDiseaseorAttack,Physical Activity,Fruits,Veggies,Heavy Alcohol Consumption,Any Health Care,No Doctor because of Cost,General Health,Mental Health,Physical Health,Difficulty Walking,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,Medium,5.0,30.0,0.0,male,4.0,Cat6,Cat8
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,Medium,0.0,0.0,0.0,male,12.0,Cat6,Cat8
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,High,0.0,10.0,0.0,male,13.0,Cat6,Cat8
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,Medium,0.0,3.0,0.0,male,11.0,Cat6,Cat8
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,Good,0.0,0.0,0.0,female,8.0,Cat5,Cat8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70687,1.0,0.0,1.0,1.0,37.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,Low,0.0,0.0,0.0,female,6.0,Cat4,Cat1
70688,1.0,0.0,1.0,1.0,29.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,Good,0.0,0.0,1.0,male,10.0,Cat3,Cat6
70689,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,Very Low,15.0,0.0,1.0,female,13.0,Cat6,Cat4
70690,1.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Low,0.0,0.0,1.0,female,11.0,Cat2,Cat4
70691,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,Good,0.0,0.0,0.0,female,9.0,Cat6,Cat2

In [33]:
# col_modes = df.mode()
# print(col_modes)

df.isnull().sum()

Diabetes_binary              0
HighBP                       0
High Cholesterol             0
Cholesterol Check            0
BMI                          1
Smoker                       0
Stroke                       0
HeartDiseaseorAttack         1
Physical Activity            1
Fruits                       2
Veggies                      1
Heavy Alcohol Consumption    1
Any Health Care              2
No Doctor because of Cost    2
General Health               1
Mental Health                1
Physical Health              1
Difficulty Walking           2
Sex                          1
Age                          1
Education                    1
Income                       1
dtype: int64

In [34]:
for col in df:
    df[col].fillna(df[col].mode()[0], inplace=True)

df.mode()

,Diabetes_binary,HighBP,High Cholesterol,Cholesterol Check,BMI,Smoker,Stroke,HeartDiseaseorAttack,Physical Activity,Fruits,Veggies,Heavy Alcohol Consumption,Any Health Care,No Doctor because of Cost,General Health,Mental Health,Physical Health,Difficulty Walking,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,Medium,0.0,0.0,0.0,female,10.0,Cat6,Cat8
1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
df.isnull().sum()

Diabetes_binary              0
HighBP                       0
High Cholesterol             0
Cholesterol Check            0
BMI                          0
Smoker                       0
Stroke                       0
HeartDiseaseorAttack         0
Physical Activity            0
Fruits                       0
Veggies                      0
Heavy Alcohol Consumption    0
Any Health Care              0
No Doctor because of Cost    0
General Health               0
Mental Health                0
Physical Health              0
Difficulty Walking           0
Sex                          0
Age                          0
Education                    0
Income                       0
dtype: int64

In [36]:
non_binary_cols = ['BMI','Mental Health','Physical Health','Age', 'General Health', 'Sex','Education','Income']
categorical_cols = ['General Health', 'Sex','Education','Income']
numerical_cols = ['BMI','Mental Health','Physical Health','Age']

In [37]:
for col, values in df.iteritems():
    print(col)
    if col not in non_binary_cols:
        
        for item in values:
            if item != 0.0 and item != 1.0:
                print(col,item)
                df.replace({col: item}, df.mode()[str(col)][0], inplace=True)
                
    elif col in categorical_cols:
        
         if col in ['Education','Income']:
                for item in values:
                    if (not isinstance(item, str)) or 'Cat' not in item:
                        print(col,item)
                        df.replace({col: item}, df.mode()[str(col)][0], inplace=True)
         elif col == 'Sex':
                for item in values:
                    if item not in ['female', 'male']:
                        print(col,item)
                        df.replace({col: item}, df.mode()[str(col)][0], inplace=True)
         elif col == 'General Health':
                for item in values:
                    if item not in ['High', 'Medium', 'Low', 'Very Low', 'Good']:
                        print(col,item)
                        df.replace({col: item}, df.mode()[str(col)][0], inplace=True)
    elif col in numerical_cols:
        
        if col in ['Physical Health','Mental Health']:
            for item in values:
                if (not isinstance(item, numbers.Number)) or item <0 or item>30:
                    print(col,item)
                    df.replace({col: item}, df.mode()[str(col)][0], inplace=True)
        elif col == 'Age':
            for item in values:
                if (not isinstance(item, numbers.Number)) or item <1 or item>122:
                    print(col,item)
                    df.replace({col: item}, df.mode()[str(col)][0], inplace=True)
        elif col == 'BMI':
            for item in values:
                 if (not isinstance(item, numbers.Number)) or item <7 or item>106:
                    print(col,item)
                    df.replace({col: item}, df.mode()[str(col)][0], inplace=True)

Diabetes_binary
HighBP
High Cholesterol
Cholesterol Check
BMI
Smoker
Stroke
HeartDiseaseorAttack
Physical Activity
Fruits
Veggies
Heavy Alcohol Consumption
Any Health Care
No Doctor because of Cost
General Health
Mental Health
Physical Health
Difficulty Walking
Sex
Age
Education
Income
Income Unknown

In [38]:
df.isnull().sum()

Diabetes_binary              0
HighBP                       0
High Cholesterol             0
Cholesterol Check            0
BMI                          0
Smoker                       0
Stroke                       0
HeartDiseaseorAttack         0
Physical Activity            0
Fruits                       0
Veggies                      0
Heavy Alcohol Consumption    0
Any Health Care              0
No Doctor because of Cost    0
General Health               0
Mental Health                0
Physical Health              0
Difficulty Walking           0
Sex                          0
Age                          0
Education                    0
Income                       0
dtype: int64

In [39]:
df.columns = df.columns.str.replace(' ','_')
df.replace(' ', '_', regex=True)
print(df.columns)
df

Index(['Diabetes_binary', 'HighBP', 'High_Cholesterol', 'Cholesterol_Check',
       'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'Physical_Activity',
       'Fruits', 'Veggies', 'Heavy_Alcohol_Consumption', 'Any_Health_Care',
       'No_Doctor_because_of_Cost', 'General_Health', 'Mental_Health',
       'Physical_Health', 'Difficulty_Walking', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='object')

,Diabetes_binary,HighBP,High_Cholesterol,Cholesterol_Check,BMI,Smoker,Stroke,HeartDiseaseorAttack,Physical_Activity,Fruits,Veggies,Heavy_Alcohol_Consumption,Any_Health_Care,No_Doctor_because_of_Cost,General_Health,Mental_Health,Physical_Health,Difficulty_Walking,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,Medium,5.0,30.0,0.0,male,4.0,Cat6,Cat8
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,Medium,0.0,0.0,0.0,male,12.0,Cat6,Cat8
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,High,0.0,10.0,0.0,male,13.0,Cat6,Cat8
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,Medium,0.0,3.0,0.0,male,11.0,Cat6,Cat8
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,Good,0.0,0.0,0.0,female,8.0,Cat5,Cat8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70687,1.0,0.0,1.0,1.0,37.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,Low,0.0,0.0,0.0,female,6.0,Cat4,Cat1
70688,1.0,0.0,1.0,1.0,29.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,Good,0.0,0.0,1.0,male,10.0,Cat3,Cat6
70689,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,Very Low,15.0,0.0,1.0,female,13.0,Cat6,Cat4
70690,1.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Low,0.0,0.0,1.0,female,11.0,Cat2,Cat4
70691,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,Good,0.0,0.0,0.0,female,9.0,Cat6,Cat2

In [40]:
# copy the data
print(df.columns)
df_max_scaled = df.copy()

# apply normalization techniques on Column 1
columns = ['BMI','Mental_Health','Physical_Health','Age']
for column in columns:
    if is_numeric_dtype(column):
        df_max_scaled[column] = df_max_scaled[column] /df_max_scaled[column].abs().max()
  
# view normalized data
# display(df_max_scaled)
df = df_max_scaled
df

Index(['Diabetes_binary', 'HighBP', 'High_Cholesterol', 'Cholesterol_Check',
       'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'Physical_Activity',
       'Fruits', 'Veggies', 'Heavy_Alcohol_Consumption', 'Any_Health_Care',
       'No_Doctor_because_of_Cost', 'General_Health', 'Mental_Health',
       'Physical_Health', 'Difficulty_Walking', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='object')

,Diabetes_binary,HighBP,High_Cholesterol,Cholesterol_Check,BMI,Smoker,Stroke,HeartDiseaseorAttack,Physical_Activity,Fruits,Veggies,Heavy_Alcohol_Consumption,Any_Health_Care,No_Doctor_because_of_Cost,General_Health,Mental_Health,Physical_Health,Difficulty_Walking,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,Medium,5.0,30.0,0.0,male,4.0,Cat6,Cat8
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,Medium,0.0,0.0,0.0,male,12.0,Cat6,Cat8
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,High,0.0,10.0,0.0,male,13.0,Cat6,Cat8
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,Medium,0.0,3.0,0.0,male,11.0,Cat6,Cat8
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,Good,0.0,0.0,0.0,female,8.0,Cat5,Cat8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70687,1.0,0.0,1.0,1.0,37.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,Low,0.0,0.0,0.0,female,6.0,Cat4,Cat1
70688,1.0,0.0,1.0,1.0,29.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,Good,0.0,0.0,1.0,male,10.0,Cat3,Cat6
70689,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,Very Low,15.0,0.0,1.0,female,13.0,Cat6,Cat4
70690,1.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Low,0.0,0.0,1.0,female,11.0,Cat2,Cat4
70691,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,Good,0.0,0.0,0.0,female,9.0,Cat6,Cat2

In [41]:
categorical_columns = ['General_Health', 'Sex','Education','Income']
for column in categorical_columns:
    tempdf = pd.get_dummies(df[column], prefix=column)
    df = pd.merge(
        left=df,
        right=tempdf,
        left_index=True,
        right_index=True,
    )
    df = df.drop(columns=column)
df

,Diabetes_binary,HighBP,High_Cholesterol,Cholesterol_Check,BMI,Smoker,Stroke,HeartDiseaseorAttack,Physical_Activity,Fruits,Veggies,Heavy_Alcohol_Consumption,Any_Health_Care,No_Doctor_because_of_Cost,Mental_Health,Physical_Health,Difficulty_Walking,Age,General_Health_Good,General_Health_High,General_Health_Low,General_Health_Medium,General_Health_Very Low,Sex_female,Sex_male,Education_Cat1,Education_Cat2,Education_Cat3,Education_Cat4,Education_Cat5,Education_Cat6,Income_Cat1,Income_Cat2,Income_Cat3,Income_Cat4,Income_Cat5,Income_Cat6,Income_Cat7,Income_Cat8
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,5.0,30.0,0.0,4.0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,12.0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,10.0,0.0,13.0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,3.0,0.0,11.0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,8.0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70687,1.0,0.0,1.0,1.0,37.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,6.0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0
70688,1.0,0.0,1.0,1.0,29.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,10.0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0
70689,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,15.0,0.0,1.0,13.0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
70690,1.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,11.0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0
70691,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,9.0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0

In [42]:
import pickle
df.to_pickle("df_file.pkl")

# **part 2**

In [43]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [44]:
all_labels = df['Diabetes_binary']
df.drop('Diabetes_binary', axis=1, inplace=True)

In [45]:
train, test, train_labels, test_labels  = train_test_split(df, all_labels,  test_size=0.2, random_state=1)
# test, validation, test_labels, validation_labels  = train_test_split(test, test_labels,  test_size=0.5, random_state=1 ,stratify=test_labels)
# train_labels, test_labels = list(train_labels), list(test_labels)

num_cols = ['BMI','Mental_Health','Physical_Health','Age']

scaler = StandardScaler()
train[num_cols] = scaler.fit_transform(train[num_cols])
test[num_cols] = scaler.transform(test[num_cols])
# validation[num_cols] = scaler.transform(validation[num_cols])

In [46]:
param = {'max_depth': 4, 'Learning_rate': 0.1, 'N_estimator': 200, 'Subsample': 0.5, 'Colsample_bytree': 1, 'Random_seed': 123, 'eval_metric': 'auc', 'Verbosity': 1}

In [47]:
# evallist = [(dval, 'eval'), (dtrain, 'train')]
df

,HighBP,High_Cholesterol,Cholesterol_Check,BMI,Smoker,Stroke,HeartDiseaseorAttack,Physical_Activity,Fruits,Veggies,Heavy_Alcohol_Consumption,Any_Health_Care,No_Doctor_because_of_Cost,Mental_Health,Physical_Health,Difficulty_Walking,Age,General_Health_Good,General_Health_High,General_Health_Low,General_Health_Medium,General_Health_Very Low,Sex_female,Sex_male,Education_Cat1,Education_Cat2,Education_Cat3,Education_Cat4,Education_Cat5,Education_Cat6,Income_Cat1,Income_Cat2,Income_Cat3,Income_Cat4,Income_Cat5,Income_Cat6,Income_Cat7,Income_Cat8
0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,5.0,30.0,0.0,4.0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1
1,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,12.0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1
2,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,10.0,0.0,13.0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1
3,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,3.0,0.0,11.0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1
4,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,8.0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70687,0.0,1.0,1.0,37.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,6.0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0
70688,0.0,1.0,1.0,29.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,10.0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0
70689,1.0,1.0,1.0,25.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,15.0,0.0,1.0,13.0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
70690,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,11.0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0
70691,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,9.0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0

In [48]:
train

,HighBP,High_Cholesterol,Cholesterol_Check,BMI,Smoker,Stroke,HeartDiseaseorAttack,Physical_Activity,Fruits,Veggies,Heavy_Alcohol_Consumption,Any_Health_Care,No_Doctor_because_of_Cost,Mental_Health,Physical_Health,Difficulty_Walking,Age,General_Health_Good,General_Health_High,General_Health_Low,General_Health_Medium,General_Health_Very Low,Sex_female,Sex_male,Education_Cat1,Education_Cat2,Education_Cat3,Education_Cat4,Education_Cat5,Education_Cat6,Income_Cat1,Income_Cat2,Income_Cat3,Income_Cat4,Income_Cat5,Income_Cat6,Income_Cat7,Income_Cat8
46935,0.0,1.0,1.0,-1.385220,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,-0.458729,-0.084531,0.0,0.142937,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
40154,1.0,0.0,1.0,0.018258,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,-0.458729,-0.580029,0.0,-0.208857,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
30416,1.0,0.0,1.0,0.158606,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,-0.458729,-0.580029,0.0,-1.264237,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0
26051,1.0,0.0,1.0,-0.964176,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,-0.458729,-0.580029,0.0,1.198318,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0
32325,1.0,1.0,1.0,-0.262438,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.402151,-0.183630,0.0,0.846524,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49100,1.0,1.0,1.0,0.158606,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,-0.335746,2.392960,0.0,0.846524,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1
20609,1.0,1.0,1.0,-0.402785,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,-0.089780,0.410967,0.0,0.494730,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
21440,0.0,0.0,1.0,-1.525567,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.156186,-0.580029,0.0,-1.616031,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1
50057,1.0,1.0,1.0,1.281388,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,-0.458729,-0.282730,1.0,0.494730,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1
5192,0.0,0.0,1.0,0.018258,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,-0.458729,-0.580029,0.0,0.142937,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1

In [49]:
test

,HighBP,High_Cholesterol,Cholesterol_Check,BMI,Smoker,Stroke,HeartDiseaseorAttack,Physical_Activity,Fruits,Veggies,Heavy_Alcohol_Consumption,Any_Health_Care,No_Doctor_because_of_Cost,Mental_Health,Physical_Health,Difficulty_Walking,Age,General_Health_Good,General_Health_High,General_Health_Low,General_Health_Medium,General_Health_Very Low,Sex_female,Sex_male,Education_Cat1,Education_Cat2,Education_Cat3,Education_Cat4,Education_Cat5,Education_Cat6,Income_Cat1,Income_Cat2,Income_Cat3,Income_Cat4,Income_Cat5,Income_Cat6,Income_Cat7,Income_Cat8
25002,1.0,0.0,1.0,0.018258,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,-0.458729,-0.580029,0.0,-2.671411,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0
45944,1.0,1.0,1.0,0.439301,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,-0.458729,-0.580029,0.0,-1.616031,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0
23894,1.0,0.0,1.0,-0.402785,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,-0.458729,-0.580029,0.0,0.142937,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0
6931,0.0,0.0,1.0,-0.683481,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,-0.458729,-0.580029,0.0,1.550111,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1
39255,0.0,1.0,1.0,-0.122090,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,-0.458729,-0.580029,0.0,0.846524,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49773,1.0,1.0,1.0,-0.402785,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,2.000930,-0.580029,0.0,0.494730,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
4164,1.0,0.0,1.0,-0.683481,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,-0.458729,-0.580029,0.0,-0.208857,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1
11688,1.0,1.0,0.0,0.298953,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.156186,-0.580029,0.0,-0.560650,0,0,0,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0
47518,1.0,0.0,1.0,0.018258,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,-0.458729,-0.580029,0.0,0.142937,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0
6265,1.0,1.0,1.0,-0.683481,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,-0.458729,-0.580029,0.0,0.142937,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1

In [50]:
# xgb_cl = xgb.XGBClassifier(random_state = 42, eval_metric='auc')
xgb_cl = xgb.XGBClassifier(**param)
# xgb_cl.set_params(**param)
xgb_cl.fit(train, train_labels)
# xgb_cl.save_model('0001.model')

XGBClassifier(Colsample_bytree=1, Learning_rate=0.1, N_estimator=200,
              Random_seed=123, Subsample=0.5, Verbosity=1, eval_metric='auc',
              max_depth=4)

In [51]:
# predict = bst.predict(dtest, iteration_range=(0, bst.best_iteration + 1))
predicton = xgb_cl.predict(test)

In [52]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, log_loss
from sklearn.metrics import roc_curve, roc_auc_score, auc

In [53]:
def calculate_metrics(actual, prediction):
    print("Accuracy: {:.3f}\nPrecision: {:.3f}\nRecall: {:.3f}\nf1_score: {:.3f}\nRoc_auc: {:.3f}".format(
        accuracy_score(actual, prediction),
        precision_score(actual, prediction),
        recall_score(actual, prediction),
        f1_score(actual, prediction),
        roc_auc_score(actual, prediction)))

In [54]:
try:
   calculate_metrics(test_labels, predicton)
except ValueError:
    pass
confusion_matrix(test_labels, predicton)

Accuracy: 0.758
Precision: 0.733
Recall: 0.802
f1_score: 0.766
Roc_auc: 0.758

array([[5102, 2039],
       [1387, 5611]])

# **part 3**

In [55]:
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import KFold, cross_val_score, train_test_split, StratifiedKFold, GridSearchCV

In [56]:
learning_rate_list = [0.02, 0.05, 0.1, 0.3]
max_depth_list = [2, 3, 4]
n_estimators_list = [100, 200, 300]
colsample_bytree = [0.8, 1]

In [57]:
def my_roc_auc_score(model, X, y): 
    return roc_auc_score(y, model.predict_proba(X)[:,1])

In [58]:
xgbc_clf = xgb.XGBClassifier(Eval_metric="auc" ,Subsample=0.5) 


param_grid = dict(learning_rate=learning_rate_list, Max_depth = max_depth_list, n_estimators=n_estimators_list, Colsample_bytree = colsample_bytree)

kfold = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

grid_search = GridSearchCV(xgbc_clf, param_grid, scoring = my_roc_auc_score, cv=kfold)

grid_result = grid_search.fit(train , train_labels)

In [59]:
pickle.dump(grid_search, open("gridsearch", 'wb'))
pickle.dump(xgbc_clf, open("classifier", 'wb'))

In [61]:
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

grid_result.cv_results_

Best: 0.828885 using {'Colsample_bytree': 0.8, 'Max_depth': 2, 'learning_rate': 0.05, 'n_estimators': 300}

{'mean_fit_time': array([ 3.58351525,  5.98555485,  9.71245408,  5.34900912,  6.64665627,
         8.79891348,  2.9879415 ,  6.72419175, 11.86779992,  3.01318423,
         7.51113502,  8.88493427,  3.01535646,  6.29396065,  9.02030301,
         3.27299301,  5.95807377,  9.15158399,  3.16483935,  5.98105558,
         8.81687697,  2.93489909,  5.80955784,  8.64934254,  3.01516589,
         5.96883361,  8.86053292,  3.28553732,  5.98701779,  8.92633828,
         3.03029799,  5.92133514,  8.99525015,  3.02722406,  5.85174243,
         8.69735408,  3.02823973,  5.94182817,  8.89534704,  3.08779271,
         6.14250517,  8.9400502 ,  3.07446114,  5.89923374,  8.93562841,
         3.01477472,  5.90067967,  8.76606933,  3.03312794,  5.9189078 ,
         9.27203266,  3.03806543,  6.15073013,  8.80556035,  3.0329202 ,
         5.93918618,  8.85708364,  2.97723635,  5.9246343 ,  8.87664421,
         3.00561539,  5.88650362,  8.74948525,  2.98698211,  6.17461324,
         8.7713875 ,  3.04465278,  5.91640973,  8.83778795,  3.09263547,
         5.84927924,  8.69089214]),
 'mean_score_time': array([0.06537747, 0.12112006, 0.19184518, 0.08713365, 0.12614465,
        0.1716427 , 0.07017303, 0.12172286, 0.16467388, 0.06439471,
        0.12321456, 0.15868282, 0.06273222, 0.11571312, 0.16929468,
        0.07149506, 0.12239075, 0.16940959, 0.07053979, 0.1177551 ,
        0.16009291, 0.06344382, 0.10961668, 0.15334638, 0.06294592,
        0.11894178, 0.16691073, 0.07735944, 0.12292306, 0.17218296,
        0.07134628, 0.11809246, 0.16204007, 0.06542261, 0.11003288,
        0.15656606, 0.06368621, 0.116328  , 0.1720527 , 0.07537977,
        0.12137087, 0.16937685, 0.07245191, 0.11881582, 0.16563058,
        0.06540044, 0.11269204, 0.15704377, 0.0632058 , 0.11485918,
        0.16965906, 0.0757393 , 0.12796092, 0.17131631, 0.06958707,
        0.1188465 , 0.15998896, 0.06577849, 0.11468267, 0.15396897,
        0.06326143, 0.1162684 , 0.17090106, 0.06826782, 0.12153157,
        0.1714282 , 0.07112575, 0.12210719, 0.15953692, 0.06557854,
        0.11147761, 0.15321557]),
 'mean_test_score': array([0.81808003, 0.82541065, 0.82731678, 0.82668303, 0.82849946,
        0.82888459, 0.8285155 , 0.82888277, 0.82865021, 0.82762063,
        0.82676531, 0.82539215, 0.81808003, 0.82541065, 0.82731678,
        0.82668303, 0.82849946, 0.82888459, 0.8285155 , 0.82888277,
        0.82865021, 0.82762063, 0.82676531, 0.82539215, 0.81808003,
        0.82541065, 0.82731678, 0.82668303, 0.82849946, 0.82888459,
        0.8285155 , 0.82888277, 0.82865021, 0.82762063, 0.82676531,
        0.82539215, 0.81808003, 0.82541065, 0.82731678, 0.82668303,
        0.82849946, 0.82888459, 0.8285155 , 0.82888277, 0.82865021,
        0.82762063, 0.82676531, 0.82539215, 0.81808003, 0.82541065,
        0.82731678, 0.82668303, 0.82849946, 0.82888459, 0.8285155 ,
        0.82888277, 0.82865021, 0.82762063, 0.82676531, 0.82539215,
        0.81808003, 0.82541065, 0.82731678, 0.82668303, 0.82849946,
        0.82888459, 0.8285155 , 0.82888277, 0.82865021, 0.82762063,
        0.82676531, 0.82539215]),
 'param_Colsample_bytree': masked_array(data=[0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8,
                    0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8,
                    0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8,
                    0.8, 0.8, 0.8, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                    1, 1, 1, 1, 1],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_Max_depth': masked_array(data=[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
                    3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
                    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
                    3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_learning_rate': masked_array(data=[0.02, 0.02, 0.02, 0.05, 0.05, 0.05, 0.1, 0.1, 0.1, 0.3,
                    0.3, 0.3, 0.02, 0.02, 0.02, 0.05, 0.05, 0.05, 0.1, 0.1,
                    0.1, 0.3, 0.3, 0.3, 0.02, 0.02, 0.02, 0.05, 0.05, 0.05,
                    0.1, 0.1, 0.1, 0.3, 0.3, 0.3, 0.02, 0.02, 0.02, 0.05,
                    0.05, 0.05, 0.1, 0.1, 0.1, 0.3, 0.3, 0.3, 0.02, 0.02,
                    0.02, 0.05, 0.05, 0.05, 0.1, 0.1, 0.1, 0.3, 0.3, 0.3,
                    0.02, 0.02, 0.02, 0.05, 0.05, 0.05, 0.1, 0.1, 0.1, 0.3,
                    0.3, 0.3],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_n_estimators': masked_array(data=[100, 200, 300, 100, 200, 300, 100, 200, 300, 100, 200,
                    300, 100, 200, 300, 100, 200, 300, 100, 200, 300, 100,
                    200, 300, 100, 200, 300, 100, 200, 300, 100, 200, 300,
                    100, 200, 300, 100, 200, 300, 100, 200, 300, 100, 200,
                    300, 100, 200, 300, 100, 200, 300, 100, 200, 300, 100,
                    200, 300, 100, 200, 300, 100, 200, 300, 100, 200, 300,
                    100, 200, 300, 100, 200, 300],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'Colsample_bytree': 0.8,
   'Max_depth': 2,
   'learning_rate': 0.02,
   'n_estimators': 100},
  {'Colsample_bytree': 0.8,
   'Max_depth': 2,
   'learning_rate': 0.02,
   'n_estimators': 200},
  {'Colsample_bytree': 0.8,
   'Max_depth': 2,
   'learning_rate': 0.02,
   'n_estimators': 300},
  {'Colsample_bytree': 0.8,
   'Max_depth': 2,
   'learning_rate': 0.05,
   'n_estimators': 100},
  {'Colsample_bytree': 0.8,
   'Max_depth': 2,
   'learning_rate': 0.05,
   'n_estimators': 200},
  {'Colsample_bytree': 0.8,
   'Max_depth': 2,
   'learning_rate': 0.05,
   'n_estimators': 300},
  {'Colsample_bytree': 0.8,
   'Max_depth': 2,
   'learning_rate': 0.1,
   'n_estimators': 100},
  {'Colsample_bytree': 0.8,
   'Max_depth': 2,
   'learning_rate': 0.1,
   'n_estimators': 200},
  {'Colsample_bytree': 0.8,
   'Max_depth': 2,
   'learning_rate': 0.1,
   'n_estimators': 300},
  {'Colsample_bytree': 0.8,
   'Max_depth': 2,
   'learning_rate': 0.3,
   'n_estimators': 100},
  {'Colsample_bytree': 0.8,
   'Max_depth': 2,
   'learning_rate': 0.3,
   'n_estimators': 200},
  {'Colsample_bytree': 0.8,
   'Max_depth': 2,
   'learning_rate': 0.3,
   'n_estimators': 300},
  {'Colsample_bytree': 0.8,
   'Max_depth': 3,
   'learning_rate': 0.02,
   'n_estimators': 100},
  {'Colsample_bytree': 0.8,
   'Max_depth': 3,
   'learning_rate': 0.02,
   'n_estimators': 200},
  {'Colsample_bytree': 0.8,
   'Max_depth': 3,
   'learning_rate': 0.02,
   'n_estimators': 300},
  {'Colsample_bytree': 0.8,
   'Max_depth': 3,
   'learning_rate': 0.05,
   'n_estimators': 100},
  {'Colsample_bytree': 0.8,
   'Max_depth': 3,
   'learning_rate': 0.05,
   'n_estimators': 200},
  {'Colsample_bytree': 0.8,
   'Max_depth': 3,
   'learning_rate': 0.05,
   'n_estimators': 300},
  {'Colsample_bytree': 0.8,
   'Max_depth': 3,
   'learning_rate': 0.1,
   'n_estimators': 100},
  {'Colsample_bytree': 0.8,
   'Max_depth': 3,
   'learning_rate': 0.1,
   'n_estimators': 200},
  {'Colsample_bytree': 0.8,
   'Max_depth': 3,
   'learning_rate': 0.1,
   'n_estimators': 300},
  {'Colsample_bytree': 0.8,
   'Max_depth': 3,
   'learning_rate': 0.3,
   'n_estimators': 100},
  {'Colsample_bytree': 0.8,
   'Max_depth': 3,
   'learning_rate': 0.3,
   'n_estimators': 200},
  {'Colsample_bytree': 0.8,
   'Max_depth': 3,
   'learning_rate': 0.3,
   'n_estimators': 300},
  {'Colsample_bytree': 0.8,
   'Max_depth': 4,
   'learning_rate': 0.02,
   'n_estimators': 100},
  {'Colsample_bytree': 0.8,
   'Max_depth': 4,
   'learning_rate': 0.02,
   'n_estimators': 200},
  {'Colsample_bytree': 0.8,
   'Max_depth': 4,
   'learning_rate': 0.02,
   'n_estimators': 300},
  {'Colsample_bytree': 0.8,
   'Max_depth': 4,
   'learning_rate': 0.05,
   'n_estimators': 100},
  {'Colsample_bytree': 0.8,
   'Max_depth': 4,
   'learning_rate': 0.05,
   'n_estimators': 200},
  {'Colsample_bytree': 0.8,
   'Max_depth': 4,
   'learning_rate': 0.05,
   'n_estimators': 300},
  {'Colsample_bytree': 0.8,
   'Max_depth': 4,
   'learning_rate': 0.1,
   'n_estimators': 100},
  {'Colsample_bytree': 0.8,
   'Max_depth': 4,
   'learning_rate': 0.1,
   'n_estimators': 200},
  {'Colsample_bytree': 0.8,
   'Max_depth': 4,
   'learning_rate': 0.1,
   'n_estimators': 300},
  {'Colsample_bytree': 0.8,
   'Max_depth': 4,
   'learning_rate': 0.3,
   'n_estimators': 100},
  {'Colsample_bytree': 0.8,
   'Max_depth': 4,
   'learning_rate': 0.3,
   'n_estimators': 200},
  {'Colsample_bytree': 0.8,
   'Max_depth': 4,
   'learning_rate': 0.3,
   'n_estimators': 300},
  {'Colsample_bytree': 1,
   'Max_depth': 2,
   'learning_rate': 0.02,
   'n_estimators': 100},
  {'Colsample_bytree': 1,
   'Max_depth': 2,
   'learning_rate': 0.02,
   'n_estimators': 200},
  {'Colsample_bytree': 1,
   'Max_depth': 2,
   'learning_rate': 0.02,
   'n_estimators': 300},
  {'Colsample_bytree': 1,
   'Max_depth': 2,
   'learning_rate': 0.05,
   'n_estimators': 100},
  {'Colsample_bytree': 1,
   'Max_depth': 2,
   'learning_rate': 0.05,
   'n_estimators': 200},
  {'Colsample_bytree': 1,
   'Max_depth': 2,
   'learning_rate': 0.05,
   'n_estimators': 300},
  {'Colsample_bytree': 1,
   'Max_depth': 2,
   'learning_rate': 0.1,
   'n_estimators': 100},
  {'Colsample_bytree': 1,
   'Max_depth': 2,
   'learning_rate': 0.1,
   'n_estimators': 200},
  {'Colsample_bytree': 1,
   'Max_depth': 2,
   'learning_rate': 0.1,
   'n_estimators': 300},
  {'Colsample_bytree': 1,
   'Max_depth': 2,
   'learning_rate': 0.3,
   'n_estimators': 100},
  {'Colsample_bytree': 1,
   'Max_depth': 2,
   'learning_rate': 0.3,
   'n_estimators': 200},
  {'Colsample_bytree': 1,
   'Max_depth': 2,
   'learning_rate': 0.3,
   'n_estimators': 300},
  {'Colsample_bytree': 1,
   'Max_depth': 3,
   'learning_rate': 0.02,
   'n_estimators': 100},
  {'Colsample_bytree': 1,
   'Max_depth': 3,
   'learning_rate': 0.02,
   'n_estimators': 200},
  {'Colsample_bytree': 1,
   'Max_depth': 3,
   'learning_rate': 0.02,
   'n_estimators': 300},
  {'Colsample_bytree': 1,
   'Max_depth': 3,
   'learning_rate': 0.05,
   'n_estimators': 100},
  {'Colsample_bytree': 1,
   'Max_depth': 3,
   'learning_rate': 0.05,
   'n_estimators': 200},
  {'Colsample_bytree': 1,
   'Max_depth': 3,
   'learning_rate': 0.05,
   'n_estimators': 300},
  {'Colsample_bytree': 1,
   'Max_depth': 3,
   'learning_rate': 0.1,
   'n_estimators': 100},
  {'Colsample_bytree': 1,
   'Max_depth': 3,
   'learning_rate': 0.1,
   'n_estimators': 200},
  {'Colsample_bytree': 1,
   'Max_depth': 3,
   'learning_rate': 0.1,
   'n_estimators': 300},
  {'Colsample_bytree': 1,
   'Max_depth': 3,
   'learning_rate': 0.3,
   'n_estimators': 100},
  {'Colsample_bytree': 1,
   'Max_depth': 3,
   'learning_rate': 0.3,
   'n_estimators': 200},
  {'Colsample_bytree': 1,
   'Max_depth': 3,
   'learning_rate': 0.3,
   'n_estimators': 300},
  {'Colsample_bytree': 1,
   'Max_depth': 4,
   'learning_rate': 0.02,
   'n_estimators': 100},
  {'Colsample_bytree': 1,
   'Max_depth': 4,
   'learning_rate': 0.02,
   'n_estimators': 200},
  {'Colsample_bytree': 1,
   'Max_depth': 4,
   'learning_rate': 0.02,
   'n_estimators': 300},
  {'Colsample_bytree': 1,
   'Max_depth': 4,
   'learning_rate': 0.05,
   'n_estimators': 100},
  {'Colsample_bytree': 1,
   'Max_depth': 4,
   'learning_rate': 0.05,
   'n_estimators': 200},
  {'Colsample_bytree': 1,
   'Max_depth': 4,
   'learning_rate': 0.05,
   'n_estimators': 300},
  {'Colsample_bytree': 1,
   'Max_depth': 4,
   'learning_rate': 0.1,
   'n_estimators': 100},
  {'Colsample_bytree': 1,
   'Max_depth': 4,
   'learning_rate': 0.1,
   'n_estimators': 200},
  {'Colsample_bytree': 1,
   'Max_depth': 4,
   'learning_rate': 0.1,
   'n_estimators': 300},
  {'Colsample_bytree': 1,
   'Max_depth': 4,
   'learning_rate': 0.3,
   'n_estimators': 100},
  {'Colsample_bytree': 1,
   'Max_depth': 4,
   'learning_rate': 0.3,
   'n_estimators': 200},
  {'Colsample_bytree': 1,
   'Max_depth': 4,
   'learning_rate': 0.3,
   'n_estimators': 300}],
 'rank_test_score': array([67, 55, 37, 49, 25,  1, 19,  7, 13, 31, 43, 61, 67, 55, 37, 49, 25,
         1, 19,  7, 13, 31, 43, 61, 67, 55, 37, 49, 25,  1, 19,  7, 13, 31,
        43, 61, 67, 55, 37, 49, 25,  1, 19,  7, 13, 31, 43, 61, 67, 55, 37,
        49, 25,  1, 19,  7, 13, 31, 43, 61, 67, 55, 37, 49, 25,  1, 19,  7,
        13, 31, 43, 61], dtype=int32),
 'split0_test_score': array([0.81827214, 0.82548188, 0.82735637, 0.8267539 , 0.82842334,
        0.82848172, 0.82846011, 0.82841696, 0.82786586, 0.82691426,
        0.82557877, 0.82387269, 0.81827214, 0.82548188, 0.82735637,
        0.8267539 , 0.82842334, 0.82848172, 0.82846011, 0.82841696,
        0.82786586, 0.82691426, 0.82557877, 0.82387269, 0.81827214,
        0.82548188, 0.82735637, 0.8267539 , 0.82842334, 0.82848172,
        0.82846011, 0.82841696, 0.82786586, 0.82691426, 0.82557877,
        0.82387269, 0.81827214, 0.82548188, 0.82735637, 0.8267539 ,
        0.82842334, 0.82848172, 0.82846011, 0.82841696, 0.82786586,
        0.82691426, 0.82557877, 0.82387269, 0.81827214, 0.82548188,
        0.82735637, 0.8267539 , 0.82842334, 0.82848172, 0.82846011,
        0.82841696, 0.82786586, 0.82691426, 0.82557877, 0.82387269,
        0.81827214, 0.82548188, 0.82735637, 0.8267539 , 0.82842334,
        0.82848172, 0.82846011, 0.82841696, 0.82786586, 0.82691426,
        0.82557877, 0.82387269]),
 'split1_test_score': array([0.81532608, 0.82293794, 0.82488921, 0.82428713, 0.82619555,
        0.82693777, 0.82631615, 0.82712677, 0.826998  , 0.82569154,
        0.82476455, 0.82346613, 0.81532608, 0.82293794, 0.82488921,
        0.82428713, 0.82619555, 0.82693777, 0.82631615, 0.82712677,
        0.826998  , 0.82569154, 0.82476455, 0.82346613, 0.81532608,
        0.82293794, 0.82488921, 0.82428713, 0.82619555, 0.82693777,
        0.82631615, 0.82712677, 0.826998  , 0.82569154, 0.82476455,
        0.82346613, 0.81532608, 0.82293794, 0.82488921, 0.82428713,
        0.82619555, 0.82693777, 0.82631615, 0.82712677, 0.826998  ,
        0.82569154, 0.82476455, 0.82346613, 0.81532608, 0.82293794,
        0.82488921, 0.82428713, 0.82619555, 0.82693777, 0.82631615,
        0.82712677, 0.826998  , 0.82569154, 0.82476455, 0.82346613,
        0.81532608, 0.82293794, 0.82488921, 0.82428713, 0.82619555,
        0.82693777, 0.82631615, 0.82712677, 0.826998  , 0.82569154,
        0.82476455, 0.82346613]),
 'split2_test_score': array([0.82064188, 0.82781213, 0.82970477, 0.82900807, 0.83087949,
        0.8312343 , 0.83077023, 0.83110458, 0.83108678, 0.83025611,
        0.82995261, 0.82883762, 0.82064188, 0.82781213, 0.82970477,
        0.82900807, 0.83087949, 0.8312343 , 0.83077023, 0.83110458,
        0.83108678, 0.83025611, 0.82995261, 0.82883762, 0.82064188,
        0.82781213, 0.82970477, 0.82900807, 0.83087949, 0.8312343 ,
        0.83077023, 0.83110458, 0.83108678, 0.83025611, 0.82995261,
        0.82883762, 0.82064188, 0.82781213, 0.82970477, 0.82900807,
        0.83087949, 0.8312343 , 0.83077023, 0.83110458, 0.83108678,
        0.83025611, 0.82995261, 0.82883762, 0.82064188, 0.82781213,
        0.82970477, 0.82900807, 0.83087949, 0.8312343 , 0.83077023,
        0.83110458, 0.83108678, 0.83025611, 0.82995261, 0.82883762,
        0.82064188, 0.82781213, 0.82970477, 0.82900807, 0.83087949,
        0.8312343 , 0.83077023, 0.83110458, 0.83108678, 0.83025611,
        0.82995261, 0.82883762]),
 'std_fit_time': array([0.65011211, 0.05300557, 1.18024224, 0.60095714, 0.60187597,
        0.0817888 , 0.01485896, 1.20859993, 1.39314829, 0.03408106,
        1.35922187, 0.0881975 , 0.00635939, 0.16025369, 0.09339446,
        0.34463454, 0.04845844, 0.01917787, 0.21042501, 0.03488363,
        0.03963774, 0.01715849, 0.00223266, 0.03771188, 0.00184988,
        0.04685043, 0.07643436, 0.2311777 , 0.0050443 , 0.13397476,
        0.02038842, 0.09141177, 0.14377427, 0.01815399, 0.06039777,
        0.07920305, 0.02150224, 0.01634964, 0.03459747, 0.10776466,
        0.17030478, 0.03258719, 0.02558086, 0.03039054, 0.07683942,
        0.02622404, 0.02669068, 0.07640983, 0.04609908, 0.06409065,
        0.34571084, 0.0512193 , 0.27858651, 0.05104444, 0.03158723,
        0.02777701, 0.06113095, 0.01177847, 0.06789907, 0.15347681,
        0.04692448, 0.10940232, 0.02308442, 0.0131276 , 0.30350287,
        0.07566377, 0.02954756, 0.03410742, 0.10084053, 0.01867789,
        0.02196195, 0.03411044]),
 'std_score_time': array([0.00048514, 0.00114854, 0.03415016, 0.00965509, 0.00128754,
        0.00408484, 0.00020205, 0.00922879, 0.00330665, 0.00062211,
        0.01706358, 0.00890309, 0.00104082, 0.0009699 , 0.00103927,
        0.00051428, 0.00142362, 0.00482672, 0.00183561, 0.00322599,
        0.00214206, 0.0004494 , 0.00261739, 0.00168289, 0.00181757,
        0.00662943, 0.00130977, 0.00937049, 0.00231133, 0.00221597,
        0.00199375, 0.00247227, 0.00279963, 0.00102043, 0.00213695,
        0.00739607, 0.00093748, 0.00194317, 0.00441436, 0.00942373,
        0.00059461, 0.00403578, 0.00151356, 0.00217598, 0.0100919 ,
        0.00129373, 0.00486486, 0.00482688, 0.00227258, 0.0022127 ,
        0.00384875, 0.00906136, 0.00459492, 0.00334519, 0.00057213,

In [63]:
param = {'Colsample_bytree': 0.8, 'Max_depth': 2, 'learning_rate': 0.05, 'n_estimators': 300}
best_clf = xgb.XGBClassifier(**param)
best_clf.fit(train, train_labels)

XGBClassifier(Colsample_bytree=0.8, Max_depth=2, learning_rate=0.05,
              n_estimators=300)

In [64]:
predicton = best_clf.predict(train)
try:
   calculate_metrics(train_labels, predicton)
except ValueError:
    pass
confusion_matrix(train_labels, predicton)

Accuracy: 0.756
Precision: 0.736
Recall: 0.799
f1_score: 0.766
Roc_auc: 0.756

array([[20099,  8106],
       [ 5711, 22637]])

In [65]:
predicton = best_clf.predict(test)
try:
   calculate_metrics(test_labels, predicton)
except ValueError:
    pass
confusion_matrix(test_labels, predicton)

Accuracy: 0.755
Precision: 0.734
Recall: 0.791
f1_score: 0.761
Roc_auc: 0.755

array([[5133, 2008],
       [1461, 5537]])

# **part 4**

In [ ]:
def plot_results_of_each_parameter():